### ISSUE TITLE
Port to fog gem

### ISSUE THREAD

**Issue by andrusha** [coderoshi/middleman-aws-deploy#1]
Hey, this is a great project, you probably already noticed that you're building alternative for https://github.com/karlfreeman/middleman-sync, which doesn't support cloudfront cache invalidation.

So I've thought you could probably simplify your code by using fog (http://fog.io/cdn/) instead of plain http requests to communicate with api.

**Comment by andrusha** [comment]
Here is my take on this problem https://github.com/andrusha/middleman-cloudfront

**Comment by coderoshi** [comment]
Good to know. I just gemified some scripts I wrote to deploy the riak docs months ago.

I think actually looked through your code, where I got the idea to use Parallel. May have been another sync project.
